#define _NUITKA_ONEFILE_BUILD_BOOL 1
#define _NUITKA_ONEFILE_CHILD_GRACE_TIME_INT 5000
#define _NUITKA_ONEFILE_COMPRESSION_BOOL 1
#define _NUITKA_ONEFILE_TEMP_BOOL 1
#define _NUITKA_ONEFILE_TEMP_SPEC "%TEMP%\\onefile_%PID%_%TIME%"
