# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nscan.proto\x12\x08\x62urp.rpc\"9\n\x0bPoc_Request\x12\x10\n\x08poc_type\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0b\n\x03poc\x18\x03 \x01(\t\"2\n\x0cPoc_Response\x12\x12\n\nis_success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t2?\n\x03poc\x12\x38\n\x07pocscan\x12\x15.burp.rpc.Poc_Request\x1a\x16.burp.rpc.Poc_ResponseB\x02P\x01\x62\x06proto3')



_POC_REQUEST = DESCRIPTOR.message_types_by_name['Poc_Request']
_POC_RESPONSE = DESCRIPTOR.message_types_by_name['Poc_Response']
Poc_Request = _reflection.GeneratedProtocolMessageType('Poc_Request', (_message.Message,), {
  'DESCRIPTOR' : _POC_REQUEST,
  '__module__' : 'scan_pb2'
  # @@protoc_insertion_point(class_scope:burp.rpc.Poc_Request)
  })
_sym_db.RegisterMessage(Poc_Request)

Poc_Response = _reflection.GeneratedProtocolMessageType('Poc_Response', (_message.Message,), {
  'DESCRIPTOR' : _POC_RESPONSE,
  '__module__' : 'scan_pb2'
  # @@protoc_insertion_point(class_scope:burp.rpc.Poc_Response)
  })
_sym_db.RegisterMessage(Poc_Response)

_POC = DESCRIPTOR.services_by_name['poc']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _POC_REQUEST._serialized_start=24
  _POC_REQUEST._serialized_end=81
  _POC_RESPONSE._serialized_start=83
  _POC_RESPONSE._serialized_end=133
  _POC._serialized_start=135
  _POC._serialized_end=198
# @@protoc_insertion_point(module_scope)
