// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scan.proto

// Protobuf Java Version: 3.25.3
package burp.rpc;

public interface Poc_ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:burp.rpc.Poc_Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_success = 1;</code>
   * @return The isSuccess.
   */
  boolean getIsSuccess();

  /**
   * <code>string result = 2;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 2;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
