// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scan.proto

// Protobuf Java Version: 3.25.3
package burp.rpc;

public interface Poc_RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:burp.rpc.Poc_Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string poc_type = 1;</code>
   * @return The pocType.
   */
  java.lang.String getPocType();
  /**
   * <code>string poc_type = 1;</code>
   * @return The bytes for pocType.
   */
  com.google.protobuf.ByteString
      getPocTypeBytes();

  /**
   * <code>string url = 2;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 2;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string poc = 3;</code>
   * @return The poc.
   */
  java.lang.String getPoc();
  /**
   * <code>string poc = 3;</code>
   * @return The bytes for poc.
   */
  com.google.protobuf.ByteString
      getPocBytes();
}
