// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scan.proto

// Protobuf Java Version: 3.25.3
package burp.rpc;

public final class Scan {
  private Scan() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_burp_rpc_Poc_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_burp_rpc_Poc_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_burp_rpc_Poc_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_burp_rpc_Poc_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nscan.proto\022\010burp.rpc\"9\n\013Poc_Request\022\020\n" +
      "\010poc_type\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022\013\n\003poc\030\003 \001(" +
      "\t\"2\n\014Poc_Response\022\022\n\nis_success\030\001 \001(\010\022\016\n" +
      "\006result\030\002 \001(\t2?\n\003poc\0228\n\007pocscan\022\025.burp.r" +
      "pc.Poc_Request\032\026.burp.rpc.Poc_ResponseB\002" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_burp_rpc_Poc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_burp_rpc_Poc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_burp_rpc_Poc_Request_descriptor,
        new java.lang.String[] { "PocType", "Url", "Poc", });
    internal_static_burp_rpc_Poc_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_burp_rpc_Poc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_burp_rpc_Poc_Response_descriptor,
        new java.lang.String[] { "IsSuccess", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
